'use client';
import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { Castle, House, Building2, Sparkles, Shuffle, ArrowUpRight, Download, ChevronDown, ChevronRight, Minus, Plus, Layers3, Ruler, DoorOpen, Grid2X2, Armchair, Tags, Maximize, Compass, BookOpen, X, Check, SlidersHorizontal, SquareDashed, MousePointer2, Map, Box, ScanLine, Footprints, Blocks, Stethoscope } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { DEFAULT_SETTINGS, FAMILIES, MATERIALS, ROOM_COLORS, ROOM_GROUPS, type Alternative, type BuildKind, type Settings, type Plan, type Family, type GenerationResult } from '@/lib/model';
import { generatePlan, newSeed } from '@/lib/architecture';
import { routeToRoom } from '@/lib/navigation';
import { DIAGNOSTICS, PlanDrawing, type Diagnostic, type DrawingOptions } from '@/components/plan-drawing';
import { getModelContext, registerBlueprintTools } from '@/lib/blueprint-tools';
import { layerSvg, voxelize, type BlockLayer, type MeshData } from '@/lib/voxels';
import { floorOutline, litematicaFile, wholeBuilding } from '@/lib/litematica';
import { LitematicaExport } from '@/components/litematica-export';
import type { ViewControls } from '@/components/building-viewer';
import BuildWorker from '../lib/build.worker?worker';

const BuildingViewer=lazy(()=>import('@/components/building-viewer'));
const initialPlan=generatePlan(DEFAULT_SETTINGS),icons={castle:Castle,manor:Building2,house:House};
type Stats={blocks:number;chunks:number;bytes:number;milliseconds:number;triangles:number};
/** What the worker reports about the finished blocks, as distinct from the plan they were built from. */
type BuiltReport={valid:boolean;issues:{code:string;severity:string;id:string;message:string}[];
  walking:{nodes:number;reached:number};lighting:{target:number;minimum:number|null;sources:number};stairs:number;repairs:number};
function saveFile(content:Blob,name:string){const url=URL.createObjectURL(content),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
async function saveSvg(svg:string,name:string,png=false){if(!png){saveFile(new Blob([svg],{type:'image/svg+xml'}),`${name}.svg`);return;}const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const img=new Image();await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject(new Error('PNG rendering failed. Please export SVG.'));img.src=url;});const canvas=document.createElement('canvas');canvas.width=2800;canvas.height=2200;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('PNG is unavailable. Please export SVG.');ctx.fillStyle='#f2efe2';ctx.fillRect(0,0,2800,2200);ctx.drawImage(img,0,0,2800,2200);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('PNG export failed.');saveFile(blob,`${name}.png`);}finally{URL.revokeObjectURL(url);}}

export default function Home(){
  const [settings,setSettings]=useState<Settings>(DEFAULT_SETTINGS),[plan,setPlan]=useState(initialPlan),[level,setLevel]=useState(0),[selected,setSelected]=useState(initialPlan.rooms.find(r=>r.kind==='hall')!.id);
  const [options,setOptions]=useState<DrawingOptions>({labels:true,furniture:true,grid:false,dimensions:true,colors:true,diagnostics:'off'});
  const [view,setView]=useState('plan'),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0});
  const [alternatives,setAlternatives]=useState<Alternative[]>([]);
  const [audit,setAudit]=useState<BuiltReport|null>(null);
  const [dialog,setDialog]=useState<'help'|'export'|'litematica'|'rooms'|'compositions'|null>(null),[notice,setNotice]=useState(''),[mobileSettings,setMobileSettings]=useState(false),[exporting,setExporting]=useState(false);
  const [busy,setBusy]=useState('Composing the reference manor…'),[failure,setFailure]=useState(''),[meshes,setMeshes]=useState<MeshData[]>([]),[stats,setStats]=useState<Stats|null>(null),[floorLayers,setFloorLayers]=useState<Record<number,BlockLayer>>({});
  const [controls,setControls]=useState<ViewControls>({roofs:true,isolate:false,explode:false,cutX:100,cutZ:100,floor:0});
  const [layerY,setLayerY]=useState(0),[layer,setLayer]=useState<BlockLayer|null>(null),[previous,setPrevious]=useState<BlockLayer|null>(null),[ghost,setGhost]=useState(false),[cell,setCell]=useState<{x:number;z:number;material:number}|null>(null);
  const activeWorker=useRef<Worker|null>(null),candidateWorker=useRef<Worker|null>(null),generation=useRef(0),activeId=useRef(0),layerRequest=useRef(0),pending=useRef<((r:GenerationResult)=>void)|null>(null);
  const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null),planRef=useRef(plan);planRef.current=plan;
  const live=useRef({plan,generate,selectFloor:(i:number)=>{switchFloor(i);setView('plan');},selectLayer:(y:number)=>{setLayerY(y);changeView('layers');}});live.current={plan,generate,selectFloor:(i:number)=>{switchFloor(i);setView('plan');},selectLayer:(y:number)=>{setLayerY(y);changeView('layers');}};
  useEffect(()=>{void generate(DEFAULT_SETTINGS);return()=>{activeWorker.current?.terminate();candidateWorker.current?.terminate();pending.current?.({ok:false,error:'Generation cancelled.'});};},[]);
  useEffect(()=>{const context=getModelContext();if(!context)return;return registerBlueprintTools(context,{read:()=>live.current.plan,generate:s=>live.current.generate(s),selectFloor:i=>live.current.selectFloor(i),selectLayer:y=>live.current.selectLayer(y)});},[]);
  useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(id);},[notice]);
  useEffect(()=>{const requestId=++layerRequest.current;if(activeWorker.current)activeWorker.current.postMessage({type:'layer',id:activeId.current,y:layerY,requestId});},[layerY,plan,stats]);
  const floor=plan.floors.find(f=>f.index===level)||plan.floors[0],room=plan.rooms.find(r=>r.id===selected),b=plan.bounds;
  const nav=plan.navigation,comp=plan.composition,route=room?routeToRoom(plan,room.id):[];
  const dirty=JSON.stringify(settings)!==JSON.stringify(plan.settings),family=FAMILIES[plan.settings.kind].find(f=>f.id===plan.family)!;
  const update=(patch:Partial<Settings>)=>setSettings(s=>({...s,...patch}));
  function generate(next:Settings=settings,only?:number):Promise<GenerationResult>{
    candidateWorker.current?.terminate();pending.current?.({ok:false,error:'Generation superseded by a newer request.'});
    const id=++generation.current;setBusy('Composing rooms and connected floors…');setFailure('');setSettings(next);
    return new Promise(resolve=>{
      pending.current=resolve;
      try{
        const worker=new BuildWorker();candidateWorker.current=worker;
        worker.onmessage=event=>{
          const message=event.data;
          if(message.type==='layer'){if(worker===activeWorker.current&&message.requestId===layerRequest.current){setLayer(message.layer);setPrevious(message.previous);}return;}
          if(id!==generation.current)return;
          if(message.type==='progress'){setBusy(message.stage);return;}
          if(message.type==='error'){setFailure(message.error);setBusy('');worker.terminate();candidateWorker.current=null;pending.current=null;resolve({ok:false,error:message.error});return;}
          if(message.type==='ready'){
            activeWorker.current?.terminate();activeWorker.current=worker;candidateWorker.current=null;activeId.current=id;
            flushSync(()=>{setPlan(message.plan);planRef.current=message.plan;setMeshes(message.meshes);setStats(message.stats);setFloorLayers(message.floorLayers);setAudit(message.audit??null);setAlternatives(message.alternatives??[]);setSettings(message.plan.settings);setLevel(0);setSelected(message.plan.rooms.find((r:Plan['rooms'][number])=>r.kind==='hall').id);setLayerY(0);setLayer(null);setZoom(1);setPan({x:0,y:0});setControls(c=>({...c,floor:0}));setBusy('');setMobileSettings(false);});
            pending.current=null;resolve({ok:true,plan:message.plan,alternatives:message.alternatives??[]});
          }
        };
        worker.onerror=()=>{if(id===generation.current){const error='The building worker could not finish. Your previous build is retained. Try a smaller composition or regenerate.';setFailure(error);setBusy('');pending.current=null;resolve({ok:false,error});worker.terminate();}};
        worker.postMessage({type:'generate',id,settings:next,only});
      }catch(cause){console.error('Generation startup:',cause);const error='Background generation is unavailable in this browser.';setFailure(error);setBusy('');resolve({ok:false,error});}
    });
  }
  function switchFloor(value:number){const f=planRef.current.floors.find(f=>f.index===value);if(f){setLevel(f.index);setSelected(f.rooms.find(r=>r.kind!=='circulation')?.id||f.rooms[0]?.id);setControls(c=>({...c,floor:f.elevation}));}}
  function selectRoom(id:string){const r=plan.rooms.find(r=>r.id===id);if(r){setSelected(id);setLevel(r.floorY/6);setControls(c=>({...c,floor:r.floorY}));}}
  function changeView(v:string){setView(v);setZoom(1);setPan({x:0,y:0});}
  function pointerDown(e:React.PointerEvent<SVGSVGElement>){if((e.target as Element).classList.contains('room-hit'))return;drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};e.currentTarget.setPointerCapture(e.pointerId);}
  function pointerMove(e:React.PointerEvent<SVGSVGElement>){if(drag.current){const rect=e.currentTarget.getBoundingClientRect(),scale=Math.max(b.w/rect.width,b.d/rect.height);setPan({x:drag.current.px+(e.clientX-drag.current.x)*scale,y:drag.current.py+(e.clientY-drag.current.y)*scale});}else if(view==='layers'&&layer){const group=e.currentTarget.querySelector('g[data-pan]') as SVGGElement;const matrix=group?.getScreenCTM();if(matrix){const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse()),x=Math.floor(point.x),z=Math.floor(point.y),run=layer.runs.find(r=>r.z===z&&x>=r.x&&x<r.x+r.length);setCell({x,z,material:run?.material||0});}}}
  const transform=`translate(${pan.x} ${pan.y}) translate(${b.x+b.w/2} ${b.z+b.d/2}) scale(${zoom}) translate(${-b.x-b.w/2} ${-b.z-b.d/2})`;
  async function exportPlan(format:'svg'|'png'|'json'|'all'|'layer-svg'|'layer-png'|'litematic'|'litematic-all'){
    setExporting(true);try{
      const slug=plan.name.toLowerCase().replaceAll(' ','-');
      if(format.startsWith('litematic')){
        // Litematica reads the file straight off disk, so it goes to the schematics folder rather than to
        // any importer: .minecraft/schematics, or the instance's own folder.
        const outline=format==='litematic';
        const schematic=outline?floorOutline(plan,floor,voxelize(plan)):wholeBuilding(plan);
        const bytes=await litematicaFile(schematic);
        saveFile(new Blob([bytes as BlobPart],{type:'application/octet-stream'}),
          outline?`${slug}-${floor.name.replaceAll(' ','-')}-outline.litematic`:`${slug}.litematic`);
      }
      else if(format==='json')saveFile(new Blob([JSON.stringify(plan,null,2)],{type:'application/json'}),`${slug}-v2.json`);
      else if(format.startsWith('layer')){if(!layer||layer.y!==layerY)throw new Error('The layer is loading. Please try again.');await saveSvg(layerSvg(layer,ghost&&previous?previous:undefined),`${slug}-Y${layerY}`,format==='layer-png');}
      else if(format==='all'){
        const pages=plan.floors.map((f,i)=>{const el=document.getElementById(`export-floor-${f.index}`)!.cloneNode(true) as SVGSVGElement;el.setAttribute('y',String(i*1100));el.setAttribute('width','1400');el.setAttribute('height','1100');return new XMLSerializer().serializeToString(el);}).join('');saveFile(new Blob([`<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="${1100*plan.floors.length}">${pages}</svg>`],{type:'image/svg+xml'}),`${slug}-all-floors.svg`);
      }else{const el=document.getElementById(`export-floor-${floor.index}`)!.cloneNode(true) as SVGSVGElement;el.removeAttribute('id');el.setAttribute('xmlns','http://www.w3.org/2000/svg');await saveSvg(new XMLSerializer().serializeToString(el),`${slug}-${floor.name.replaceAll(' ','-')}`,format==='png');}
      // A build that failed its own physical checks still exports — but nobody should find that out in the world.
      const unsound=format==='litematic-all'&&audit&&!audit.valid?` It failed ${audit.issues.filter(i=>i.severity==='error').length} of the walkable checks — see the walkable score.`:'';
      setNotice('Your blueprint has been exported.'+unsound);setDialog(null);
    }catch(error){setNotice(error instanceof Error?error.message:'Export failed.');}finally{setExporting(false);}
  }
  const floorPicker=<select className="floor-picker" aria-label="Select floor" value={floor.index} onChange={e=>switchFloor(Number(e.target.value))}>{[...plan.floors].reverse().map(f=><option key={f.index} value={f.index}>{f.name} · Y {f.elevation}</option>)}</select>;
  return <div className="app-shell">
    <header className="app-header"><a className="brand" href="/" aria-label="Keepwright home"><span className="brand-mark"><Castle size={25} strokeWidth={1.6}/></span><span>keepwright<span className="brand-period">.</span></span></a><nav className="top-nav" aria-label="Main navigation"><span className="nav-active"><SquareDashed size={16}/>Build studio</span><button onClick={()=>setDialog('help')}><BookOpen size={16}/>Field guide</button></nav><div className="header-right"><span className="private-label"><span/>Imagine the building. Build every block.</span><button className="button button-outline" onClick={()=>setDialog('export')}><Download size={16}/>Export<ChevronDown size={14}/></button></div></header>
    <div className="studio-layout"><aside className={`settings-panel ${mobileSettings?'mobile-open':''}`} aria-label="Build settings"><div className="settings-heading"><div><span className="eyebrow">THE FOUNDATION</span><h2>Build settings</h2></div><button className="icon-button mobile-close" aria-label="Close settings" onClick={()=>setMobileSettings(false)}><X size={18}/></button><SlidersHorizontal className="heading-icon" size={19}/></div><div className="settings-body">
      <section className="setting-section"><span className="field-title">Building type</span><div className="build-types" role="group" aria-label="Building type">{(['castle','manor','house'] as const).map(kind=>{const Icon=icons[kind];return <button key={kind} aria-pressed={settings.kind===kind} className={`type-card ${settings.kind===kind?'chosen':''}`} onClick={()=>update({kind,family:'auto'})}><Icon size={26} strokeWidth={1.3}/><span>{kind[0].toUpperCase()+kind.slice(1)}</span>{settings.kind===kind&&<Check className="type-check" size={11}/>}</button>;})}</div><label className="family-label" htmlFor="family">Architectural family</label><select id="family" value={settings.family} onChange={e=>update({family:e.target.value as Family})}><option value="auto">Automatic · let the seed decide</option>{FAMILIES[settings.kind].map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></section>
      <section className="setting-section"><div className="field-row"><label className="field-title" htmlFor="size">Footprint budget</label><span className="value-badge">{settings.size} blocks</span></div><input id="size" className="native-range" type="range" min="48" max="512" step="8" value={settings.size} onChange={e=>update({size:+e.target.value})}/><div className="range-labels"><span>Compact</span><span>512-block complex</span></div><p className="field-hint">Larger sites add households and ranges.</p></section>
      <section className="setting-section floor-setting"><div><span className="field-title">Maximum storeys</span><p className="field-hint">Ranges end at different heights</p></div><div className="stepper"><button aria-label="Fewer floors" disabled={settings.floors<=1} onClick={()=>update({floors:settings.floors-1})}><Minus size={14}/></button><output>{settings.floors}</output><button aria-label="More floors" disabled={settings.floors>=8} onClick={()=>update({floors:settings.floors+1})}><Plus size={14}/></button></div></section>
      <section className="setting-section"><div className="field-row"><label className="field-title" htmlFor="organic">Organic character</label><span className="numeric-value">{settings.organic}%</span></div><input id="organic" className="native-range" type="range" min="0" max="100" step="5" value={settings.organic} onChange={e=>update({organic:+e.target.value})}/><div className="range-labels"><span>Composed</span><span>Grown over centuries</span></div></section>
      <section className="setting-section feature-section"><span className="field-title">Make room for</span>{(['courtyard','chapel','garden','cellar','essentials'] as const).map(key=><label className="feature-row checkbox-row" key={key}><span>{{courtyard:'Enclosed court',chapel:'Chapel',garden:'Kitchen garden',cellar:'Selected cellars',essentials:'Rooms a player needs'}[key]}</span><input type="checkbox" checked={settings[key]} onChange={e=>update({[key]:e.target.checked})}/></label>)}</section>
      <section className="setting-section seed-section"><div className="field-row"><label htmlFor="seed" className="field-title">World seed</label><button className="text-button" onClick={()=>update({seed:newSeed()})}><Shuffle size={13}/>Randomize</button></div><div className="seed-input"><span>#</span><input id="seed" maxLength={64} value={settings.seed} onChange={e=>update({seed:e.target.value})} onKeyDown={e=>{if(e.key==='Enter')void generate();}}/></div><p className="field-hint">Same seed. Same settings. Same architecture.</p></section>
    </div><div className="generate-footer"><button className="button generate-button" onClick={()=>void generate()}><Sparkles size={17}/>{busy?'Restart generation':dirty?'Generate new build':'Generate build'}<ArrowUpRight size={17}/></button><button className="surprise-button" onClick={()=>void generate({...settings,seed:newSeed()})}><Shuffle size={13}/>Surprise me</button><button className="surprise-button" onClick={()=>void generate(DEFAULT_SETTINGS)}>Open reference manor</button></div></aside>
    <main className="workspace"><div className="workspace-heading"><div><div className="eyebrow breadcrumb">BUILD STUDIO <ChevronRight size={11}/> YOUR BLUEPRINT</div><h1>{plan.name}<span className="draft-badge">ARCHITECTURE V2</span></h1><p>{family.description}</p><div className={`navigability ${nav.transits.length?'compromised':''}`} title={nav.transits.length?`A household is forced to cross ${nav.transits.map(t=>t.name).join(', ')}`:'No room has to be crossed to reach another'}><Footprints size={13}/><strong>{nav.score}</strong><span>navigability</span><em>{nav.transits.length?`${nav.transits.length} forced crossing${nav.transits.length===1?'':'s'}`:'no forced crossings'} · {nav.loops} alternative route{nav.loops===1?'':'s'} · {nav.maxDepth} doors at deepest{nav.compromises?` · ${nav.compromises} door${nav.compromises===1?'':'s'} a household would not have cut`:''}</em></div><div className="navigability composition" title="How the volumes stand together: how far the composition reaches from the hall, how much of its ground it uses, and how many rooms have an outside wall"><Blocks size={13}/><strong>{comp.score}</strong><span>composition</span><em>{comp.volumes} volume{comp.volumes===1?'':'s'} · {comp.yards} yard{comp.yards===1?'':'s'} · {comp.reach} deep from the hall · {Math.round(comp.frontage*100)}% with an outside wall</em></div>{audit&&<div className={`navigability walkability ${audit.valid?'':'compromised'}`} title={audit.issues.length?audit.issues.slice(0,4).map(i=>i.message).join(' '):'Every room can be walked to from the door, every doorway is clear, every window glazed and every stair connected'}><Stethoscope size={13}/><strong>{Math.round(100*audit.walking.reached/Math.max(1,audit.walking.nodes))}%</strong><span>walkable</span><em>{audit.walking.reached.toLocaleString()} of {audit.walking.nodes.toLocaleString()} standing positions reachable from the door · {audit.stairs} stair{audit.stairs===1?'':'s'} · darkest room light {audit.lighting.minimum??'—'} of {audit.lighting.target} · {audit.repairs} repair{audit.repairs===1?'':'s'}{audit.issues.length?` · ${audit.issues.length} to answer for`:''}</em></div>}{alternatives.length>1&&<button className="text-button alternatives-button" onClick={()=>setDialog('compositions')}><Shuffle size={13}/>{alternatives.length} compositions for this seed</button>}</div><button className="button button-outline settings-mobile-toggle" onClick={()=>setMobileSettings(true)}><SlidersHorizontal size={16}/>Settings</button><div className="seed-display"><span>WORLD SEED</span><code>{plan.settings.seed}</code></div></div>
      <div className="plan-summary"><span><Ruler size={15}/><strong>{plan.width} × {plan.depth}</strong> blocks</span><i/><span><Layers3 size={15}/><strong>{plan.components.length}</strong> ranges</span><i/><span><DoorOpen size={15}/><strong>{plan.rooms.filter(r=>!['circulation','stairs'].includes(r.kind)).length}</strong> rooms</span><i/><span><Castle size={15}/><strong>{plan.floors.length}</strong> levels</span><span className="status-label"><span/>{busy?'Building…':dirty?'Settings changed':'Connected & validated'}</span></div>
      {busy&&<div className="generation-status" role="status"><span className="spinner"/>{busy}<small>You can keep exploring the current building.</small></div>}{failure&&<div className="generation-error" role="alert">{failure}</div>}
      <div className="plan-workspace"><div className="plan-toolbar"><div className="studio-tabs" role="tablist" aria-label="Blueprint views">{[{id:'plan',label:'Floor plan',icon:Map},{id:'3d',label:'3D cutaway',icon:Box},{id:'layers',label:'Block layers',icon:Grid2X2},{id:'stack',label:'Floor set',icon:Layers3}].map(tab=><button key={tab.id} role="tab" aria-selected={view===tab.id} onClick={()=>changeView(tab.id)}><tab.icon size={15}/><span>{tab.label}</span></button>)}</div>{view==='plan'&&<div className="drawing-tools">{([{key:'grid',label:'Grid',icon:Grid2X2},{key:'labels',label:'Labels',icon:Tags},{key:'furniture',label:'Furniture',icon:Armchair},{key:'dimensions',label:'Dimensions',icon:Ruler}] as const).map(tool=><button key={tool.key} aria-label={`Toggle ${tool.label.toLowerCase()}`} aria-pressed={options[tool.key]} className={`tool-button ${options[tool.key]?'active':''}`} onClick={()=>setOptions(o=>({...o,[tool.key]:!o[tool.key]}))}><tool.icon size={16}/><span>{tool.label}</span></button>)}<label className="tool-select" title={DIAGNOSTICS.find(d=>d.id===(options.diagnostics??'off'))!.hint}><Stethoscope size={16}/><span className="sr-only">Show the generator&rsquo;s working</span><select value={options.diagnostics??'off'} onChange={e=>setOptions(o=>({...o,diagnostics:e.target.value as Diagnostic}))}>{DIAGNOSTICS.map(d=><option key={d.id} value={d.id}>{d.id==='off'?'Show working':d.name}</option>)}</select></label></div>}</div>
        {(view==='plan'||view==='layers')&&<div className="canvas-panel"><div className="canvas-top">{view==='plan'?floorPicker:<div className="layer-selector"><button aria-label="Previous block layer" disabled={layerY<=plan.minY} onClick={()=>setLayerY(y=>y-1)}><Minus size={15}/></button><label>Y <input aria-label="Block elevation" type="number" min={plan.minY} max={plan.maxY} value={layerY} onChange={e=>setLayerY(Math.max(plan.minY,Math.min(plan.maxY,Math.round(Number(e.target.value)))))}/></label><button aria-label="Next block layer" disabled={layerY>=plan.maxY} onClick={()=>setLayerY(y=>y+1)}><Plus size={15}/></button><label className="ghost-check"><input type="checkbox" checked={ghost} onChange={e=>setGhost(e.target.checked)}/>Ghost Y−1</label></div>}<div className="compass"><span>N · −Z</span><Compass size={28} strokeWidth={.9}/></div></div>
          <svg className="floor-svg" viewBox={`${b.x} ${b.z} ${b.w} ${b.d}`} aria-label={view==='plan'?`${plan.name}, ${floor.name}`:`Block layer Y ${layerY}`} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}><g data-pan="true" transform={transform}>{view==='plan'?<PlanDrawing plan={plan} floor={floor} options={options} selected={selected} onSelect={selectRoom} layer={floorLayers[floor.elevation]}/>:layer?<><defs><pattern id="block-grid" width="1" height="1" patternUnits="userSpaceOnUse"><path d="M1 0H0V1" stroke="#6f7767" strokeWidth=".07" fill="none"/></pattern></defs>{ghost&&previous?.runs.map((r,i)=><rect key={`g${i}`} x={r.x} y={r.z} width={r.length} height="1" fill={MATERIALS[r.material].color} opacity=".2"/>)}{layer.runs.map((r,i)=><rect key={i} x={r.x} y={r.z} width={r.length} height="1" fill={MATERIALS[r.material].color}/>)}<rect x={b.x} y={b.z} width={b.w} height={b.d} fill="url(#block-grid)"/>{cell&&<rect x={cell.x} y={cell.z} width="1" height="1" fill="none" stroke="#e19535" strokeWidth=".22"/>}</>:<text x={b.x+b.w/2} y={b.z+b.d/2} textAnchor="middle" fill="#718368" fontSize="2">Preparing block layer…</text>}</g></svg>
          <div className="canvas-bottom"><div className="scale-key"><Ruler size={16}/><span>{view==='layers'?(cell?`X ${cell.x} · Y ${layerY} · Z ${cell.z} · ${MATERIALS[cell.material].name}`:`Y ${layerY} · Each square is one block`):`1 square = 1 Minecraft block · Y ${floor.elevation}`}</span></div><div className="zoom-controls"><button aria-label="Zoom out" disabled={zoom<=.5} onClick={()=>setZoom(z=>Math.max(.5,z/1.35))}><Minus size={15}/></button><output>{Math.round(zoom*100)}%</output><button aria-label="Zoom in" disabled={zoom>=12} onClick={()=>setZoom(z=>Math.min(12,z*1.35))}><Plus size={15}/></button><i/><button aria-label="Fit plan to view" onClick={()=>{setZoom(1);setPan({x:0,y:0});}}><Maximize size={15}/></button></div></div>
        </div>}
        {view==='3d'&&<><div className="viewer-controls">{floorPicker}{(['roofs','isolate','explode'] as const).map(key=><label key={key}><input type="checkbox" checked={controls[key]} onChange={e=>setControls(c=>({...c,[key]:e.target.checked}))}/>{{roofs:'Show roofs',isolate:'Isolate floor',explode:'Explode floors'}[key]}</label>)}<label>Cut X<input aria-label="X cutaway" type="range" min="0" max="100" value={controls.cutX} onChange={e=>setControls(c=>({...c,cutX:+e.target.value}))}/></label><label>Cut Z<input aria-label="Z cutaway" type="range" min="0" max="100" value={controls.cutZ} onChange={e=>setControls(c=>({...c,cutZ:+e.target.value}))}/></label><button className="text-button" onClick={()=>setControls(c=>({...c,cutX:100,cutZ:100,isolate:false,explode:false}))}>Reset cuts</button></div>{meshes.length?<Suspense fallback={<div className="three-stage loading-view">Loading 3D…</div>}><BuildingViewer plan={plan} meshes={meshes} controls={controls} selected={selected} onSelect={selectRoom}/></Suspense>:<div className="three-stage loading-view">Preparing the building…</div>}</>}
        {view==='stack'&&<div className="stack-panel"><div className="stack-heading"><Layers3 size={20}/><div><h3>One building. Different lives on every level.</h3><p>Hatched areas are open to below. Grey silhouettes are roofs beneath this level.</p></div></div><div className="floor-stack">{[...plan.floors].reverse().map(f=><button className="stack-card" key={f.index} onClick={()=>{switchFloor(f.index);changeView('plan');}}><div><span>{f.index<0?'B':String(f.index).padStart(2,'0')}</span><strong>{f.name}</strong><small>Y {f.elevation}</small><ArrowUpRight size={16}/></div><svg viewBox={`${b.x} ${b.z} ${b.w} ${b.d}`} aria-label={f.name}><PlanDrawing plan={plan} floor={f} options={{...options,labels:false,dimensions:false}} prefix={`stack-${f.index}`} layer={floorLayers[f.elevation]}/></svg></button>)}</div></div>}
        {view==='layers'&&layer&&<div className="material-legend">{Object.entries(layer.counts).map(([id,count])=><span key={id}><i style={{background:MATERIALS[+id].color}}/>{MATERIALS[+id].name}<strong>{count.toLocaleString()}</strong></span>)}{!layer.runs.length&&<span>This elevation is empty.</span>}<input className="layer-scrubber" aria-label="Layer scrubber" type="range" min={plan.minY} max={plan.maxY} value={layerY} onChange={e=>setLayerY(+e.target.value)}/></div>}
        <div className="plan-bottom-bar"><span><MousePointer2 size={13}/>{view==='3d'?'Drag to orbit · Right-drag to pan · Scroll to zoom':view==='layers'?'Hover for coordinates · Drag to pan · Export this layer':'Select a room to explore · Drag to pan'}</span><button onClick={()=>setDialog('rooms')}>Room directory <span>{floor.rooms.length}</span><ArrowUpRight size={14}/></button></div>
      </div>
      <div className="room-detail" aria-live="polite">{room?<><span className="room-swatch" style={{background:ROOM_COLORS[room.kind]}}><DoorOpen size={20} strokeWidth={1.3}/></span><div className="room-detail-title"><span className="eyebrow">{ROOM_GROUPS[room.kind]}</span><h3>{room.name}</h3></div><div className="room-dimensions"><strong>{room.bounds.w-1} × {room.bounds.d-1} × {room.ceilingY-room.floorY-1}</strong><span>blocks · floor Y {room.floorY}</span></div><p>{room.description}</p>
        {route.length>1&&<div className="room-route"><span className="eyebrow"><Footprints size={12}/>Walk from the entrance · {route.length-1} door{route.length===2?'':'s'}</span><ol>{route.map((step,i)=><li key={step.id+String(i)}><button className={step.id===selected?'here':''} onClick={()=>selectRoom(step.id)}>{step.name}</button></li>)}</ol></div>}</>:<p>Select a room to inspect its dimensions and how it is reached.</p>}</div>
      <footer className="workspace-footer"><span><ScanLine size={13}/>Minecraft blocks · Flat sites · Manual building</span><span>{stats?`${stats.blocks.toLocaleString()} blocks · ${plan.generatorVersion}`:'Architecture version 2'}</span></footer>
    </main></div>
    {notice&&<div className="toast" role="status"><Check size={17}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={14}/></button></div>}
    <Dialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null);}}><DialogContent className={`studio-dialog ${dialog==='rooms'?'directory-dialog':''}`}><DialogHeader><DialogTitle>{dialog==='help'?'A field guide to your next build':dialog==='export'?'Take your blueprint with you':dialog==='litematica'?'Lay the walls out before you build them':dialog==='compositions'?'Other estates this seed composed':'Room directory'}</DialogTitle><DialogDescription>{dialog==='help'?'From a household to a sprawling fantasy estate.':dialog==='export'||dialog==='litematica'?`${plan.name} · ${view==='layers'?`Y ${layerY}`:floor.name}`:dialog==='compositions'?'The search keeps every composition it considered. The same attempt of the same seed always builds the same estate.':`${floor.name} · ${floor.rooms.length} spaces`}</DialogDescription></DialogHeader>
      {dialog==='help'&&<div className="guide-content"><ol><li><strong>Choose an architectural family.</strong>A hall with crosswings, a fortified residence, or a house grown through additions. Organic character changes attachments and proportions.</li><li><strong>Read the building vertically.</strong>Switch floors to see galleries, tall-room voids and smaller upper levels. Open 3D, hide roofs, then move the X and Z cuts through the building.</li><li><strong>Build one layer at a time.</strong>Y is the height of the block. Hover over a layer for X/Z coordinates. Ghost the previous layer and export a PNG or SVG with its material counts.</li><li><strong>Take it into the world.</strong>Export the floor outline as a .litematic, put it in your Minecraft schematics folder and load it in Litematica. Stone brick is wall, glass is a light, planks mark each doorway. Outline markers give you the same walls at whatever size you want to stand inside, one floor or all of them at once, and the complete building exports every block of it.</li></ol><div className="guide-note"><BookOpen size={20}/><p>The reference manor follows the relationship of a medieval open hall, solar wing and service end. Six-block storey spacing leaves five interior blocks. Seeds are deterministic within generator version 2.</p></div></div>}
      {dialog==='export'&&<div className="export-options"><button disabled={exporting} onClick={()=>setDialog('litematica')}><Blocks size={22}/><span><strong>Outline markers · Litematica</strong><small>One floor or every floor, at the scale and height you want to stand inside</small></span><ArrowUpRight size={16}/></button>{([{id:'litematic',name:'Floor outline · Litematica',detail:`${floor.name}: wall course, doorways and lights, to build from in game`},{id:'litematic-all',name:'Complete building · Litematica',detail:'Every block of it — roofs, masonry, lights and fittings — exactly as the 3D view shows it'},{id:'png',name:'Floor plan · PNG',detail:'High-resolution image for this floor'},{id:'svg',name:'Floor plan · SVG',detail:'Crisp lines at any scale'},{id:'all',name:'Complete floor set · SVG',detail:'Every level, including selected cellars'},{id:'json',name:'Complete building · JSON',detail:'Versioned rooms, elevations and block geometry'},{id:'layer-svg',name:`Block layer Y ${layerY} · SVG`,detail:'Exact blocks, coordinates and material legend'},{id:'layer-png',name:`Block layer Y ${layerY} · PNG`,detail:'A printable image of the selected layer'}] as const).map(item=><button key={item.id} disabled={exporting||(item.id.startsWith('layer')&&!layer)} onClick={()=>void exportPlan(item.id)}><Download size={22}/><span><strong>{item.name}</strong><small>{item.detail}</small></span><ArrowUpRight size={16}/></button>)}</div>}
      {dialog==='compositions'&&<div className="export-options">{alternatives.map(alt=><button key={alt.attempt} disabled={busy!==''||alt.state==='chosen'||alt.state==='rejected'} onClick={()=>{setDialog(null);void generate(settings,alt.attempt);}}>
        <Blocks size={22}/>
        <span><strong>{alt.volumes} volume{alt.volumes===1?'':'s'} · {alt.rooms} rooms{alt.yards?` · ${alt.yards} yard${alt.yards===1?'':'s'}`:''}</strong>
        <small>{alt.state==='chosen'?'The one you are looking at':alt.state==='rejected'?`Refused: ${alt.issue??'it does not stand up'}`:alt.state==='unexamined'?`Ranked below the one chosen · navigability ${alt.navigation}, composition ${alt.composition}`:`Sound · navigability ${alt.navigation}, composition ${alt.composition}`}</small></span>
        {alt.state==='chosen'?<Check size={16}/>:alt.state==='rejected'?<X size={16}/>:<ArrowUpRight size={16}/>}
      </button>)}</div>}
      {dialog==='litematica'&&<LitematicaExport key={plan.signature} plan={plan} floorIndex={floor.index}/>}
      {dialog==='rooms'&&<div className="room-directory">{floor.rooms.map(r=><button key={r.id} className={selected===r.id?'selected':''} onClick={()=>{selectRoom(r.id);setDialog(null);}}><span className="directory-dot" style={{background:ROOM_COLORS[r.kind]}}/><span><strong>{r.name}</strong><small>{plan.components.find(c=>c.id===r.componentId)?.name}</small></span><span>{r.bounds.w-1} × {r.bounds.d-1}<small>Y {r.floorY} → {r.ceilingY}</small></span><ArrowUpRight size={16}/></button>)}</div>}
    </DialogContent></Dialog>
    <div className="export-drawings" aria-hidden="true">{plan.floors.map(f=><svg key={f.index} id={`export-floor-${f.index}`} xmlns="http://www.w3.org/2000/svg" width="1400" height="1100" viewBox={`${b.x} ${b.z-6} ${b.w} ${b.d+12}`}><rect x={b.x} y={b.z-6} width={b.w} height={b.d+12} fill="#f2efe2"/><text x={b.x+8} y={b.z-2} fontFamily="Georgia" fontSize="2.6" fill="#345a43">{plan.name} · {f.name} · Y {f.elevation}</text><PlanDrawing plan={plan} floor={f} options={options} prefix={`export-${f.index}`} layer={floorLayers[f.elevation]}/><text x={b.x+8} y={b.z+b.d+3} fontFamily="sans-serif" fontSize="1.4" fill="#718368">KEEPWRIGHT · 1 square = 1 block · {plan.settings.seed} · generator 2.0</text></svg>)}</div>
  </div>;
}
