'use client';
import { Children, cloneElement, isValidElement, type ReactNode, type ReactElement } from 'react';
import { ROOM_COLORS, type Floor, type Plan, type Room, type Point } from '@/lib/model';
import type { BlockLayer } from '@/lib/voxels';

export type DrawingOptions={labels:boolean;furniture:boolean;grid:boolean;dimensions:boolean;colors:boolean};
export function preciseSvg(node:ReactNode):ReactNode {return Children.map(node,child=>{if(!isValidElement(child))return child;const el=child as ReactElement<Record<string,unknown>>,props:Record<string,unknown>={};if(typeof el.type==='string')for(const [k,v] of Object.entries(el.props)){if(typeof v==='number'&&Number.isFinite(v))props[k]=Number(v.toFixed(5));else if(typeof v==='string'&&['d','transform','points','viewBox'].includes(k))props[k]=v.replace(/-?\d+(?:\.\d+)?(?:e[-+]?\d+)?/gi,n=>String(Number(Number(n).toFixed(5))));}if(el.props.children!==undefined)props.children=preciseSvg(el.props.children as ReactNode);return cloneElement(el,props);});}
const polygonPath=(p:Point[])=>p.length?`M${p.map(v=>`${v.x},${v.z}`).join('L')}Z`:'';
const rectPath=(x:number,z:number,w:number,d:number)=>`M${x} ${z}h${w}v${d}h${-w}Z`;
const lines=(name:string)=>{const words=name.split(' ');return name.length>14&&words.length>1?[words.slice(0,Math.ceil(words.length/2)).join(' '),words.slice(Math.ceil(words.length/2)).join(' ')]:[name];};
function Furniture({room}:{room:Room}){return <g fill="#f6eedb" stroke="#857b66" strokeWidth=".14">{room.furniture.map((f,i)=><g key={i}><rect x={f.x} y={f.z} width={f.w} height={f.d}/>{f.type==='bed'&&<><rect x={f.x+.3} y={f.z+.3} width={f.w-.6} height=".8" rx=".15"/><path d={`M${f.x} ${f.z+1.5}h${f.w}`}/></>}{f.type==='shelf'&&Array.from({length:f.w},(_,k)=><path key={k} d={`M${f.x+k+.4} ${f.z}v${f.d}`}/>)}{f.type==='hearth'&&<path d={`M${f.x+.3} ${f.z+.2}l${f.w-.6} ${f.d-.4}m0 ${-f.d+.4}l${-f.w+.6} ${f.d-.4}`}/>}</g>)}</g>;}
export function PlanDrawing({plan,floor,options,selected,onSelect,prefix='plan',layer}:{plan:Plan;floor:Floor;options:DrawingOptions;selected?:string;onSelect?:(id:string)=>void;prefix?:string;layer?:BlockLayer}){
  const b=plan.bounds,y=floor.elevation;
  const walls=layer?layer.runs.filter(r=>['wall','chimney'].includes(r.kind)).map(r=>rectPath(r.x,r.z,r.length,1)).join(''):plan.walls.filter(w=>w.y<=y+2&&w.y+w.h>y+2).map(w=>rectPath(w.x,w.z,w.w,w.d)).join('');
  return preciseSvg(<g>
    <defs><pattern id={`${prefix}-grid`} width="1" height="1" patternUnits="userSpaceOnUse"><path d="M1 0H0V1" fill="none" stroke="#a89e86" strokeWidth=".055" opacity=".4"/></pattern><pattern id={`${prefix}-void`} width="2" height="2" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><path d="M0 0V2" stroke="#aea185" strokeWidth=".1"/></pattern><pattern id={`${prefix}-wood`} width="3" height="2" patternUnits="userSpaceOnUse"><path d="M0 0H3M1.5 0V2" stroke="#9b8b6c" strokeWidth=".06" opacity=".45"/></pattern></defs>
    {floor.roofComponents.map(id=>{const c=plan.components.find(c=>c.id===id)!;return <g key={id} opacity=".28"><path d={polygonPath(c.polygon)} fill="#929b98" stroke="#636d66" strokeWidth=".3"/><text x={c.bounds.x+c.bounds.w/2} y={c.bounds.z+c.bounds.d/2} textAnchor="middle" fontFamily="Georgia" fontSize="1.3" fill="#364f43">Roof below</text></g>;})}
    {y===0&&plan.blocks.filter(block=>block.kind==='ground').map((r,i)=><rect key={i} x={r.x} y={r.z} width={r.w} height={r.d} fill={r.material===7?'#c0c9a4':'#d8c9aa'} stroke="#95a17b" strokeWidth=".12"/>)}
    {y===0&&plan.courts.map(c=><text key={c.id} x={c.bounds.x+c.bounds.w*.65} y={c.bounds.z+c.bounds.d-8} fontSize="2" fontFamily="Georgia" fontStyle="italic" fill="#8b957a" textAnchor="middle">{c.name}</text>)}
    {floor.voids.map(v=><g key={v.id}><path d={polygonPath(v.polygon)+v.holes.map(h=>rectPath(h.x,h.z,h.w,h.d)).join('')} fill={`url(#${prefix}-void)`} fillRule="evenodd" stroke="#aa9c81" strokeWidth=".2" strokeDasharray="1 1"/><text x={v.bounds.x+v.bounds.w/2} y={v.bounds.z+v.bounds.d/2} textAnchor="middle" fontFamily="Georgia" fontSize="1.5" fontStyle="italic" fill="#9a8460">Open to hall below<tspan x={v.bounds.x+v.bounds.w/2} dy="2">{v.ceilingY} block ceiling</tspan></text></g>)}
    {floor.rooms.map(r=><g key={r.id}><path d={polygonPath(r.polygon)} fill={options.colors?ROOM_COLORS[r.kind]:'#eee4cd'}/><path d={polygonPath(r.polygon)} fill={`url(#${prefix}-wood)`}/>{r.holes.map((h,i)=><rect key={i} x={h.x} y={h.z} width={h.w+1} height={h.d+1} fill="#b0b4a4"/>)}{options.furniture&&<Furniture room={r}/>}</g>)}
    <path d={walls} fill="#707566"/>
    {plan.openings.filter(o=>o.y<=y+3&&o.y+o.height>y+1).map(o=>{const isX=o.axis==='x',d=o.width;return <g key={o.id}>{!layer&&<rect x={o.x} y={o.z} width={isX?1:d} height={isX?d:1} fill={o.type==='window'?'#b9d5d6':'#ede6d5'}/>}<path d={o.type==='window'?(isX?`M${o.x+.5} ${o.z}v${d}`:`M${o.x} ${o.z+.5}h${d}`):(isX?`M${o.x+.5} ${o.z}h${d}a${d} ${d} 0 0 1 ${-d} ${d}`:`M${o.x} ${o.z+.5}v${d}a${d} ${d} 0 0 0 ${d} ${-d}`)} fill="none" stroke={o.type==='window'?'#597e84':'#8d7c5f'} strokeWidth=".15"/></g>;})}
    {plan.stairs.filter(st=>st.fromY===y||st.toY===y).map(st=>{const b=st.bounds,up=st.fromY===y;return <g key={st.id} stroke="#616b50" strokeWidth=".13"><rect x={b.x+3} y={b.z+3} width="2" height="6" fill="#d6d7c0"/>{Array.from({length:7},(_,i)=><path key={i} d={`M${b.x+3} ${b.z+3+i}h2`}/>)}<path d={`M${b.x+4} ${b.z+3.4}v5m-0.6-1l.6 1 .6-1`} fill="none" strokeWidth=".22"/><text x={b.x+1} y={b.z+5} fontSize=".8" stroke="none" fill="#63714f">{up?'UP':'DN'}</text></g>;})}
    {options.grid&&<rect x={b.x} y={b.z} width={b.w} height={b.d} fill={`url(#${prefix}-grid)`} pointerEvents="none"/>}
    {floor.rooms.map(r=>{const size=r.kind==='circulation'?.9:r.kind==='hall'?1.65:1.15,cx=r.bounds.x+r.bounds.w/2,cz=r.bounds.z+r.bounds.d/2;return <g key={`label-${r.id}`}><path className="room-hit" data-room-id={r.id} d={polygonPath(r.polygon)} fill={selected===r.id?'#4e7d5033':'transparent'} stroke={selected===r.id?'#3e6d48':'none'} strokeWidth=".45" onClick={()=>onSelect?.(r.id)} tabIndex={onSelect?0:undefined} role={onSelect?'button':undefined} aria-label={`${r.name}, ${r.bounds.w-1} by ${r.bounds.d-1} blocks, Y ${r.floorY}`} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect?.(r.id);}}}/>{options.labels&&r.kind!=='stairs'&&<text x={cx} y={cz} fontSize={size} fontFamily="Georgia,serif" textAnchor="middle" fill="#404d3d" style={{paintOrder:'stroke',stroke:'#f5efdf',strokeWidth:.35,pointerEvents:'none'}}>{lines(r.name).map((line,i)=><tspan key={i} x={cx} dy={i?size*1.2:0}>{line}</tspan>)}{options.dimensions&&r.kind!=='circulation'&&<tspan x={cx} dy={size*1.3} fontFamily="sans-serif" fontSize={size*.65} fill="#7e836d">{r.bounds.w-1} × {r.bounds.d-1}</tspan>}</text>}</g>;})}
    {options.dimensions&&<g fill="#81906d" stroke="#8e977b" strokeWidth=".12" fontFamily="sans-serif" fontSize="1.5"><path d={`M${b.x+8} ${b.z+3}h${b.w-16}m0-1v2M${b.x+8} ${b.z+2}v2`}/><text x={b.x+b.w/2} y={b.z+1.7} stroke="none" textAnchor="middle">{plan.width} blocks</text><text x={b.x+b.w-3} y={b.z+b.d/2} stroke="none" textAnchor="middle" transform={`rotate(90 ${b.x+b.w-3} ${b.z+b.d/2})`}>{plan.depth} blocks</text></g>}
  </g>);
}
